# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equilibrium0.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(".QWidget{\n"
"    background-color:#CCEEFF;\n"
"}\n"
".QTextBrowser{\n"
"    background-color:#E0FFFF;\n"
"    font-size:14px\n"
"}\n"
".QComboBox{\n"
"    background-color:    #F5F5F5;\n"
"    font-size:15px;\n"
"}\n"
".QLabel{\n"
"    font-size:15px;\n"
"    font-weight:490;\n"
"    \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.verticalLayout.addWidget(self.textBrowser_1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_2.addWidget(self.textBrowser_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_3.addWidget(self.textBrowser_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_4.addWidget(self.textBrowser_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setObjectName("button")
        self.horizontalLayout_4.addWidget(self.button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("QLabel{\n"
"    font-size:11px;\n"
"    font-weight:12;\n"
"    font-family:Microsoft YaHei;\n"
"\n"
"}")
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Equilibrium Calculator__version 0.0"))
        self.label.setText(_translate("MainWindow", "Decision Maker 1"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "アメリカ"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "日本"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "ドイツ"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "イギリス"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "シンガポール"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "スイス"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "スウェーデン"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "フランス"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "中国"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "アラブ首長国連邦"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "サウジアラビア"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "インド"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "ロシア"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "ブラジル"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "インドネシア"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "エジプト"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "ルワンダ"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "ブータン"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "ミャンマー"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "ガンビア"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "中央アフリカ"))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "ギニア"))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "ザンビア"))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "ウガンダ"))
        self.label_2.setText(_translate("MainWindow", "Decision Maker 2"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "アメリカ"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "日本"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "ドイツ"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "イギリス"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "シンガポール"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "スイス"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "スウェーデン"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "フランス"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "中国"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "アラブ首長国連邦"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "サウジアラビア"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "インド"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "ロシア"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "ブラジル"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "インドネシア"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "エジプト"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "ルワンダ"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "ブータン"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "ミャンマー"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "ガンビア"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "中央アフリカ"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "ギニア"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "ザンビア"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "ウガンダ"))
        self.label_3.setText(_translate("MainWindow", "利得表"))
        self.textBrowser_1.setPlaceholderText(_translate("MainWindow", "利得行列"))
        self.label_4.setText(_translate("MainWindow", "頂点以外のナッシュ均衡"))
        self.textBrowser_2.setPlaceholderText(_translate("MainWindow", "混合戦略のナッシュ均衡"))
        self.label_5.setText(_translate("MainWindow", "頂点のナッシュ均衡"))
        self.textBrowser_3.setPlaceholderText(_translate("MainWindow", "頂点のナッシュ均衡"))
        self.label_6.setText(_translate("MainWindow", "動学的均衡状態"))
        self.textBrowser_4.setPlaceholderText(_translate("MainWindow", "動学的均衡状態"))
        self.button.setText(_translate("MainWindow", "Calculate"))
        self.label_7.setText(_translate("MainWindow", "Copyright ©2020-2021 KOKO, All Rights Reserved."))
